### ISSUE TITLE
Provide facility to decode shortMessage, in BaseSM, so that the Pdu.toString() method can print something human readable

### ISSUE THREAD

**Issue by aaronjwhiteside** [twitter/cloudhopper-smpp#10]
Provide facility to decode the shortMessage, in BaseSM, so that the Pdu.toString() method can print something human readable.

Akin to the PduTranscoderContext that supports translating command status's and custom tlv tags into human readable text.

Perhaps a new method like PduTranscoderContext.decodeShortMessage( byte[] shortMessage, byte dataCoding ) and a default implementation that decodes based on the SMPP spec?

**Comment by jjlauer** [comment]
Cleaning up old issues.  Open to a PR if you think it would be helpful.
