### ISSUE TITLE
How I should receive multipart messages?

### ISSUE THREAD

**Issue by MaxSD81** [twitter/cloudhopper-smpp#122]
Hello,

I have CloudHopper SMPP server, at this moment I can receive a simple short messages.

if (pduRequest.getCommandId() == SmppConstants.CMD_ID_SUBMIT_SM) {
    SubmitSm request = (SubmitSm) pduRequest;
    request.getShortMessage();
    ....
}

But what I should do to receive long (Multipart) message? I don't know what object I have to use ... Help me, please.

Many thanks.

**Comment by deacix** [comment]
Hi! Do you have a solution for this problem?

**Comment by MaxSD81** [comment]
Hi, no.
