### ISSUE TITLE
SubmitMultiSm capabilities?

### ISSUE THREAD

**Issue by williamd1618** [twitter/cloudhopper-smpp#18]
Hi everyone,

I've recently begun the migration of my organization's legacy messaging platform, leveraging logica smpp, onto ch-smpp.  I've noticed that it appears to be missing the SubmitMultiSm pdu does not exist in the library.

According to the smpp 3.4 spec:

<i>The maximum message length which can be specified in sm_length field (see section 5.2.21) is 254 octets. If an ESME wishes to submit a message of length greater than 254 octets, the sm_length field must be set to NULL and the message_payload optional parameter must be populated with the message length value and user data.
SMPP supports extended message lengths in the submit_sm, submit_multi, data_sm and deliver_sm PDUs.</i>

How is SubmitMultiSm supported, for instance with UTF-16 messages?

Thanks.

dan

**Comment by lafod** [comment]
Hello Guys 

I currently use this method to send both short and long messages for a SMPP server that support it

public synchronized String sendSMSMessage(String aMessage,
            String aSentFromNumber, String aSendToNumber,
            boolean requestDeliveryReceipt) {
        byte[] textBytes = CharsetUtil.encode(aMessage,
                CharsetUtil.CHARSET_ISO_8859_1);

```
    try {
        SubmitSm submitMsg = new SubmitSm();

        // add delivery receipt if enabled.
        if (requestDeliveryReceipt) {
            submitMsg
                    .setRegisteredDelivery(SmppConstants.REGISTERED_DELIVERY_SMSC_RECEIPT_REQUESTED);
        }
        submitMsg.setSourceAddress(new Address((byte) 0x03, (byte) 0x00,
                aSentFromNumber));
        submitMsg.setDestAddress(new Address((byte) 0x01, (byte) 0x01,
                aSendToNumber));
         if (textBytes != null && textBytes.length > 255) {
             submitMsg.addOptionalParameter(new Tlv(SmppConstants.TAG_MESSAGE_PAYLOAD, textBytes, "message_payload"));
         }else{
             submitMsg.setShortMessage(textBytes);
         }

        logger.debug("About to send message to " + aSendToNumber
                + ", Msg is :: " + aMessage + ", from :: "
                + aSentFromNumber);

        SubmitSmResp submitResp = smppSession.submit(submitMsg, 15000);

        logger.debug("Message sent to " + aSendToNumber
                + " with message id " + submitResp.getMessageId());
        return submitResp.getMessageId();
    } catch (Exception ex) {
        logger.error("Exception sending message [Msg, From, To] :: ["
                + aMessage + ", " + aSentFromNumber + ", " + aSendToNumber,
                ex);
    }

    logger.debug("Message **NOT** sent to " + aSendToNumber);
    return "Message Not Submitted to " + aSendToNumber;
}
```
