### ISSUE TITLE
Login credentials displayed in Log upon Bind - how to disable?

### ISSUE THREAD

**Issue by tester5** [twitter/cloudhopper-smpp#26]
Hi,

Think the subject says what I'm trying to achieve.  I noticed that the username and password is in free text when performing a bind and want to know how to turn this off so no sensitive information is written to the logs when the bind occurs.

I'm hoping there's an easy fix for this that I'm not aware of.

**Comment by xgp** [comment]
Please submit a pull request for these changes.
