### ISSUE TITLE
Submit after Deliver

### ISSUE THREAD

**Issue by JoseChavez** [twitter/cloudhopper-smpp#38]
Hi. He wants to implement the following functionality in USSD:

- Enquire_link send and enquire_link_resp every 1 second
- Ussd session is initiated from the phone by dialing *123# + send
- Ussd gateway receives the request and sends to the application client a deliver_sm
- The application client receives deliver_sm, stopping enquire_link and send a submit_sm
- Wait to submit_sm_resp
- Send deliver_sm_resp
- Continue send enquire_link untils receives other deliver_sm

The problem is the following:

- The first time, wait to submit_sm_resp is successful
- The second time, wait for the submit_sm_resp failure (unable to get response)
- The third time, wait to submit_sm_resp is successful
- The fourth time, wait for the submit_sm_resp failure (unable to get response)

What could be causing this behavior? Could someone help me with a code that does what I need?

PS: Sorry for my English, I only speak Spanish

**Comment by xgp** [comment]
Please attach the code so we can help you debug.

**Comment by tijanibro** [comment]
Hello JoseChavez Have you been able to resolve this?

**Comment by JoseChavez** [comment]
This was a long time ago. I am no longer in the project and I do not remember how I solved it. I'm sorry
