### ISSUE TITLE
Sending message longer than 160 characters using UDH

### ISSUE THREAD

**Issue by foreverdeepak** [twitter/cloudhopper-smpp#49]
Hi Joe,

First of all, Happy new year to you. Hope, you are doing good.

We are using cloudhopper-smpp to submit the SMS to SMSC. But, SMSC has a restriction that we cannot send the SMS longer than 160 characters. If you want then you have to set the UDH. I was looking for some example/documentation, but did not find any. Can you please help us with some code snippet where we can send the long messages using UDH.

Best Regards,
Deepak

**Comment by jjlauer** [comment]
Closing this issue as the discussion above provides lots of useful info for folks interested in splitting SMS.  Lots of various ways depending on the SMSC.

**Comment by shuklaabhi** [comment]
UDH is not supported in CDMA networks. Is there any other way we can send message larger than 160 both GSM and CDMA networks.

`http://support.nowsms.com/discus/messages/12/60148.html`

According to SMPP doc we can use TLV message payload and sar_msg_ref_num, sar_segment_seqnum and sar_total_segments and set short_message to null. 
I tried it but it didn't work
