### ISSUE TITLE
Long Message Split and 134 character issues

### ISSUE THREAD

**Issue by ihtisham20** [twitter/cloudhopper-smpp#50]
We are using SMPP cloud-hopper library to SMS long long messages to SMS gateway Innovativetxt.com, but it seems like when we split following the long message To 140 bytes each part. The number of characters in each message gets to 134 character.

However industry standard is kind of 153 character shall be for each part of GSM Encoded long message. Is it something wrong we are doing by having only 134 character when we split via 140 byte? If we trying to submit greater than 140 bytes message, the gateway provider rejects it with message over-sized message body.

It seems like the Cloudhopper message split utility is doing message split based on 8 bit encoding instead of 7 bit GSM 0.038 encoding.   

Any thought how to have message split based on 7 bit GSM encoding?

**Comment by xgp** [comment]
Answered at: http://stackoverflow.com/questions/21098643/smpp-submit-long-message-and-message-split
