### ISSUE TITLE
How to check messages which have sent from other clients?

### ISSUE THREAD

**Issue by vietnguyen01** [twitter/cloudhopper-smpp#52]
Assuming I want to test receiving message between clients so I create a server and 2 clients. To run server, I used the command "make server". Then in other machine, a client connected to my server and send 1 message to other client which has phone number "123456" using following code

<pre>
<code>
submit0.setSourceAddress(new Address((byte)0x03, (byte)0x00, "654321"));
submit0.setDestAddress(new Address((byte)0x01, (byte)0x01, "123456"));
submit0.setShortMessage(textBytes);

SubmitSmResp submitResp = session0.submit(submit0, 10000); 
</code>
</pre>

How can client which has phone number "123456" check message from phone number "654321"?

**Comment by xgp** [comment]
You can see the message delivered in the server logs. If you are asking how to do routing between two ESME clients, that is something you can build with this library, but not something that is included.
