### ISSUE TITLE
Incorrect server shutdown in demos?

### ISSUE THREAD

**Issue by krasa** [twitter/cloudhopper-smpp#60]
Is there some reason why only 
```
	smppServer.stop();
```
is called, and not 
```
	smppServer.destroy();
	monitorExecutor.shutdown();
```

I would expect to see #stop at some demo which actually shows rerunning of the server.

**Comment by xgp** [comment]
Good catch. Changed in a0f4a1683f97ea304cf888708a7c0e1fdb814d86.
