### ISSUE TITLE
DefaultSmppServer ignores ExecutorService it's constructed with

### ISSUE THREAD

**Issue by maciej** [twitter/cloudhopper-smpp#63]
I've noticed while reading the code of [DefaultSmppServer (line 115)](https://github.com/twitter/cloudhopper-smpp/blob/master/src/main/java/com/cloudhopper/smpp/impl/DefaultSmppServer.java#L115) that the executor parameter is never used.
I'm not sure if this is intended behaviour.

**Comment by xgp** [comment]
Good catch. The use of the ExecutorService got orphaned with Netty changes. This is no longer relevant in the Netty 4 implementation.
