### ISSUE TITLE
Receiving and concatenating long message to cloudhopper server.

### ISSUE THREAD

**Issue by wsimukoko** [twitter/cloudhopper-smpp#66]
Hi Folks

How do i receive split long message from an smpp client in cloudhopper. We are using the library to receipt messages and forward to SMSC.

Kind Regards

William

**Comment by xgp** [comment]
Concatenated messages should have the SMPP optional parameters (sar_msg_ref_num, sar_total_segments, and sar_segements_seqnum) set. See the SMPP 3.4 spec, Section 2.2.4.2 for definitions.

**Comment by Buchafwe** [comment]
Hi 
Normally this comes as GSM Short Message Service User Data, UDH header will come as a part of a message appended as first 5 bytes of the message, to get these parameters you need to read each byte, eg. the first char (int) charAt(0) will have the UDH length

Regards,
Daniel.

**Comment by ashutosh-singh-git** [comment]
what if i have same sequence no. for all the concatenated messages?
