### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by wizardjedi** [twitter/cloudhopper-smpp#70]
Hi, folks.

Is there any news about new version with netty 4 support?

thx

**Comment by xgp** [comment]
Happy new year! 6.0.0-netty4-beta-1 has been released to Maven Central. Please test and report back any problems. We will release the formal 6.0.0 version in a few weeks, and all subsequent versions will require Netty 4.

    <dependency>
      <groupId>com.cloudhopper</groupId>
      <artifactId>ch-smpp</artifactId>
      <version>6.0.0-netty4-beta-1</version>
    </dependency>

**Comment by wizardjedi** [comment]
Great news!!!
