### ISSUE TITLE
How to get DR back from SMSC

### ISSUE THREAD

**Issue by satyadoorva** [twitter/cloudhopper-smpp#8]
Hi, 

I am looking into the source code , and am unable to figure out if we can receive the DR back from SMSC using cloudhopper.

Can anyone please guide me on that? 

Thanks

**Comment by klassounski-daitan** [comment]
Hi there! 
I got a question.
Suppose I am sending a message and I want to get a Delivery Receipt...
Which field should I use to identify that a Delivery Receipt belongs to a certain message?
I mean, I send a SubmitSm and get a DeliverSm, which field is common to both of them?

**Comment by Buchafwe** [comment]
Hi Kirill;
For each submitSM either sync or async you get back messageID from the SMSC, the same messageID will be returned in the deliverSM DLR request to your smpp client

**Comment by klassounski-daitan** [comment]
Thanks @Buchafwe! This was helpful!

**Comment by pelegk2** [comment]
d
