### ISSUE TITLE
Is it possible   to send one sms to multiple recipients using  cloudhopper-smpp ? If yes may I know how to implement ...

### ISSUE THREAD

**Issue by batman09** [twitter/cloudhopper-smpp#83]

**Comment by jjlauer** [comment]
You're asking for "Submit Multi" -- which is technically an SMPP pdu but I've never seen it used in the real world.  Thus, this library does not include support for it.  I've never seen an SMSC that really likes them -- so you just need to send multiple Submit Sm requests with the same short message to multiple recipients.
