### ISSUE TITLE
Is it possible to recieve sms using cloudhopper clients ?

### ISSUE THREAD

**Issue by gruntday** [twitter/cloudhopper-smpp#84]
We use cloud-hopper client to send messages to operator smsc however same connection can receive messages from operator when someone use this connected short-code (as an example send sms to 7777)

Currently all received messages / DLRs always detected as DeliverSm

 if(pduRequest.isRequest() && pduRequest.getClass() == DeliverSm.class)

Is there any way to differentiate between Delivery Receipt and Messages ?

Appreciate your help

**Comment by jjlauer** [comment]
Absolutely.

SmppUtil class is your friend.  The unit tests of the project are actually helpful in demoing a test of whether a DeliverSm is a receipt.

https://github.com/twitter/cloudhopper-smpp/blob/master/src/test/java/com/cloudhopper/smpp/util/SmppUtilTest.java
